### ISSUE TITLE
Traffic search tool

### ISSUE THREAD

**Issue by matan1398** [HurricaneLabs/TA-checkpoint-cef#2]
The logs of the firewall appear in any other tab in the app, but nothing in the traffic search tool. It waits for input but the input is “*” and the firewall address is All, plus it doesn’t change when you change the time to display. Thanks in advance

**Comment by matan1398** [comment]
Also it doesn’t work on the firewall managent tab

**Comment by tomkopchak** [comment]
This TA doesn't have any views or dashboards, only knowledge objects.  Is it possible that you are looking at a different app?
